# 留出验证

In [9]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [10]:
def get_model():
    return null

In [5]:
train_data.shape

(25000,)

In [7]:
data = train_data
data.shape

(25000,)

In [8]:
import numpy as np
num_validation_samples = 10000

np.random.shuffle(data)

validation_data = data[:num_validation_samples]
data = data[num_validation_samples:]

training_data = data[:]

# K折交叉验证

In [13]:
# k = 4
# num_validation_samples = len(data) // k

# np.random.shuffle(data)

# validation_scores = []
# for fold in range(k):
#     validation_data = data[num_validation_samples * fold: 
#                           num_validation_samples * (fold + 1)]
#     training_data = data[:num_validation_samples] + data[num_validation_samples * (fold + 1):]
#     model = get_model()

# 正则化

In [15]:
from keras import layers
from keras import models
from keras import regularizers

In [16]:
model = models.Sequential()
model.add(layers.Dense(16, kernel_regularizer=regularizers.l2(0.001),
                       activation='relu', input_shape=(10000, )))
model.add(layers.Dense(16, kernel_regularizer=regularizers.l2(0.001),
                       activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

# Dropout

In [24]:
batch_size = 512
features = 100

layer_output = np.ones((batch_size, features))

In [25]:
layer_output.shape

(512, 100)

In [26]:
layer_output

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [27]:
layer_output *= np.random.randint(0, high=2, size=layer_output.shape)

In [28]:
layer_output

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 1., 1.]])

numpy.random.randint(low, high=None, size=None, dtype='l')
这个方法产生离散均匀分布的整数，这些整数大于等于low，小于high

In [29]:
np.random.randint(0, high=2, size=layer_output.shape)

array([[0, 0, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 1]])