In [1]:
from keras.datasets import mnist

In [6]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 134s 12us/step


In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
len(train_images)

60000

In [9]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [11]:
test_images.shape

(10000, 28, 28)

In [12]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [13]:
from keras import models
from keras import layers

In [14]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28, )))
network.add(layers.Dense(10, activation='softmax'))

In [15]:
network.compile(optimizer='rmsprop', 
                loss='categorical_crossentropy', 
                metrics=['accuracy'])

In [16]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [17]:
from keras.utils import to_categorical

In [18]:
train_labels = to_categorical(train_labels)
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [19]:
train_labels.shape

(60000, 10)

In [20]:
test_labels = to_categorical(test_labels)
test_labels.shape

(10000, 10)

In [21]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 4s 67us/step - loss: 0.2545 - acc: 0.9262
Epoch 2/5
60000/60000 [==============================] - 4s 64us/step - loss: 0.1024 - acc: 0.9703
Epoch 3/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.0685 - acc: 0.9796
Epoch 4/5
60000/60000 [==============================] - 4s 63us/step - loss: 0.0497 - acc: 0.9847
Epoch 5/5
60000/60000 [==============================] - 4s 64us/step - loss: 0.0375 - acc: 0.9888


In [22]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 0s 42us/step
test_acc: 0.9803
